//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroSafra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastroSafra()
        {
            this.CadastroASTECs = new HashSet<CadastroASTEC>();
            this.CadastroBQRespostas = new HashSet<CadastroBQResposta>();
            this.CadastroOrcamentoAnaliticoes = new HashSet<CadastroOrcamentoAnalitico>();
        }
    
        public int ID { get; set; }
        public string SafraData { get; set; }
        public string NomeSafra { get; set; }
        public Nullable<bool> SafraPrevista { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroASTEC> CadastroASTECs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroBQResposta> CadastroBQRespostas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroOrcamentoAnalitico> CadastroOrcamentoAnaliticoes { get; set; }
    }
}
