//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastroUsuarios()
        {
            this.CadastroBQRespostas = new HashSet<CadastroBQResposta>();
            this.CadastroOrcamentoAnaliticoes = new HashSet<CadastroOrcamentoAnalitico>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public string DataExpedicao { get; set; }
        public string CPF { get; set; }
        public string DataNascimento { get; set; }
        public string Naturalidade { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public string Endereco { get; set; }
        public string CEP { get; set; }
        public string RendaMensal { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Ocupacao { get; set; }
        public string Grau { get; set; }
        public string Formacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroBQResposta> CadastroBQRespostas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroOrcamentoAnalitico> CadastroOrcamentoAnaliticoes { get; set; }
    }
}
