//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroASTEC
    {
        public int ID { get; set; }
        public decimal AstecValor { get; set; }
        public int AstecSafra { get; set; }
    
        public virtual CadastroSafra CadastroSafra { get; set; }
    }
}
