//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroEtapa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastroEtapa()
        {
            this.CadastroOrcamentoAnaliticoes = new HashSet<CadastroOrcamentoAnalitico>();
        }
    
        public int ID { get; set; }
        public string EtapaNome { get; set; }
        public Nullable<short> EtapaOrdem { get; set; }
        public bool EtapaAtiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroOrcamentoAnalitico> CadastroOrcamentoAnaliticoes { get; set; }
    }
}
