//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastroItem()
        {
            this.CadastroItemOrcamentoes = new HashSet<CadastroItemOrcamento>();
        }
    
        public int ID { get; set; }
        public string ItemNome { get; set; }
        public string ItemEspecificacao { get; set; }
        public bool ItemAtivo { get; set; }
        public string ItemUnidadeMedida { get; set; }
        public string ItemTipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroItemOrcamento> CadastroItemOrcamentoes { get; set; }
    }
}
