//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroBQResposta
    {
        public int ID { get; set; }
        public int BQRespostaPergunta { get; set; }
        public string BQRespostaResposta { get; set; }
        public int BQRespostaSafra { get; set; }
        public int BQRespostaUsuarioID { get; set; }
    
        public virtual CadastroBancoQuestoes CadastroBancoQuesto { get; set; }
        public virtual CadastroSafra CadastroSafra { get; set; }
        public virtual CadastroUsuarios CadastroUsuario { get; set; }
    }
}
