//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroBancoQuestoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastroBancoQuestoes()
        {
            this.CadastroBQRespostas = new HashSet<CadastroBQResposta>();
        }
    
        public int ID { get; set; }
        public int BancoQuestoesTipo { get; set; }
        public string BancoQuestoesPergunta { get; set; }
        public bool BancoQuestoesAtivo { get; set; }
    
        public virtual CadastroBQTipo CadastroBQTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroBQResposta> CadastroBQRespostas { get; set; }
    }
}
