//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroOrcamentoAnalitico
    {
        public int ID { get; set; }
        public int OrcamentoAnaliticoEtapa { get; set; }
        public int OrcamentoAnaliticoTipoEtapa { get; set; }
        public Nullable<int> OrcamentoAnaliticoItemOrcamento { get; set; }
        public int OrcamentoAnaliticoSafra { get; set; }
        public int OrcamentoAnaliticoUsuarioID { get; set; }
        public bool OrcamentoAnaliticoAtiva { get; set; }
        public Nullable<int> OrcamentoAnaliticoItemTipo { get; set; }
        public Nullable<System.DateTime> OrcamentoAnaliticoMesInicio { get; set; }
        public Nullable<System.DateTime> OrcamentoAnaliticoMesFim { get; set; }
    
        public virtual CadastroSafra CadastroSafra { get; set; }
        public virtual CadastroUsuarios CadastroUsuario { get; set; }
        public virtual CadastroEtapa CadastroEtapa { get; set; }
        public virtual CadastroItemOrcamento CadastroItemOrcamento { get; set; }
        public virtual CadastroTipoEtapa CadastroTipoEtapa { get; set; }
    }
}
