//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroItemOrcamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadastroItemOrcamento()
        {
            this.CadastroOrcamentoAnaliticoes = new HashSet<CadastroOrcamentoAnalitico>();
        }
    
        public int ID { get; set; }
        public int ItemOrcamentoItem { get; set; }
        public int ItemOrcamentoQuantidade { get; set; }
        public int ItemOrcamentoUnidade { get; set; }
        public double ItemOrcamentoQuantidadePorHectar { get; set; }
        public double ItemOrcamentoValorUnitario { get; set; }
        public Nullable<System.DateTime> ItemOrcamentoCadastradoEm { get; set; }
        public bool ItemOrcamentoAtiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CadastroOrcamentoAnalitico> CadastroOrcamentoAnaliticoes { get; set; }
        public virtual CadastroItem CadastroItem { get; set; }
    }
}
