//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    
    public partial class Filhos
    {
        public string Nome { get; set; }
        public string Idade { get; set; }
    }
}
