//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCPProjetosEntities : DbContext
    {
        public SCPProjetosEntities()
            : base("name=SCPProjetosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CadastroASTEC> CadastroASTEC { get; set; }
        public virtual DbSet<CadastroBancoQuestoes> CadastroBancoQuestoes { get; set; }
        public virtual DbSet<CadastroBQResposta> CadastroBQResposta { get; set; }
        public virtual DbSet<CadastroBQTipo> CadastroBQTipo { get; set; }
        public virtual DbSet<CadastroEtapa> CadastroEtapa { get; set; }
        public virtual DbSet<CadastroTipoEtapa> CadastroTipoEtapa { get; set; }
        public virtual DbSet<TotaisMarca> TotaisMarca { get; set; }
        public virtual DbSet<ViewAgendaAplicacoes> ViewAgendaAplicacoes { get; set; }
        public virtual DbSet<ViewProdutos> ViewProdutos { get; set; }
        public virtual DbSet<ViewServicos> ViewServicos { get; set; }
        public virtual DbSet<CadastroSafra> CadastroSafra { get; set; }
        public virtual DbSet<ViewRespostasPerguntas> ViewRespostasPerguntas { get; set; }
        public virtual DbSet<CadastroUsuarios> CadastroUsuarios { get; set; }
        public virtual DbSet<ViewOrcamentoAnalitico> ViewOrcamentoAnalitico { get; set; }
        public virtual DbSet<CadastroItemOrcamento> CadastroItemOrcamento { get; set; }
        public virtual DbSet<CadastroOrcamentoAnalitico> CadastroOrcamentoAnalitico { get; set; }
        public virtual DbSet<CadastroItem> CadastroItem { get; set; }
    }
}
