//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewServicos
    {
        public string TipoEtapaNome { get; set; }
        public int ID { get; set; }
        public string ServicoNome { get; set; }
        public Nullable<bool> ServicoAtiva { get; set; }
        public string ServicoUnidadeMedida { get; set; }
        public Nullable<int> ServicoEtapa { get; set; }
    }
}
