//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOrcamentoAnalitico
    {
        public int ID { get; set; }
        public Nullable<int> OrcamentoAnaliticoItemOrcamento { get; set; }
        public Nullable<int> OrcamentoAnaliticoItemTipo { get; set; }
        public int OrcamentoItem { get; set; }
        public int OrcamentoUnidadeMedida { get; set; }
        public double AreaPrevista { get; set; }
        public int OrcamentoAnaliticoQuantidadeItemOrcamento { get; set; }
        public double OrcamentoAnaliticoQuantidadePorHectarItemOrcamento { get; set; }
        public double OrcamentoAnaliticoValorUnitarioItemOrcamento { get; set; }
        public int OrcamentoAnaliticoSafra { get; set; }
        public int OrcamentoAnaliticoUsuarioID { get; set; }
        public bool OrcamentoAnaliticoAtiva { get; set; }
        public double CustoHectar { get; set; }
        public double CustoTotal { get; set; }
        public Nullable<System.DateTime> OrcamentoAnaliticoMesInicio { get; set; }
        public Nullable<System.DateTime> OrcamentoAnaliticoMesFim { get; set; }
        public string EtapaNome { get; set; }
        public Nullable<short> EtapaOrdem { get; set; }
        public string TipoEtapaNomes { get; set; }
    }
}
