//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProdutos
    {
        public int ID { get; set; }
        public string MarcaNome { get; set; }
        public string MarcaEspecificacao { get; set; }
        public bool MarcaAtiva { get; set; }
        public string TipoEtapaNome { get; set; }
        public string MarcaUnidadeMedida { get; set; }
        public Nullable<int> MarcaEtapa { get; set; }
    }
}
