//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Areas.Projetos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAgendaAplicacoes
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public double AreaPrevista { get; set; }
        public Nullable<System.DateTime> MesInicio { get; set; }
        public Nullable<System.DateTime> MesFim { get; set; }
    }
}
