//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroTerraSolo
    {
        public int ID { get; set; }
        public int TerraSoloEspecificacao { get; set; }
        public double TerraSoloArea { get; set; }
        public string TerraSoloCaracteristicas { get; set; }
        public string TerraSoloClasse { get; set; }
        public Nullable<bool> TerraSoloAtiva { get; set; }
        public int TerraSoloFazenda { get; set; }
        public int TerraSoloMicrorregiao { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public int TerraSoloTipoCultura { get; set; }
        public int TerraSoloMicrorregiaoTerra { get; set; }
        public int TerraSoloUsuario { get; set; }
    
        public virtual CadastroFazenda CadastroFazenda { get; set; }
        public virtual CadastroUsuarios CadastroUsuarios { get; set; }
        public virtual TerraSolo TerraSolo { get; set; }
    }
}
