//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroUsuarios
    {
        public CadastroUsuarios()
        {
            this.CadastroBenfeitoria = new HashSet<CadastroBenfeitoria>();
            this.CadastroBensDireitos = new HashSet<CadastroBensDireitos>();
            this.CadastroClientes = new HashSet<CadastroClientes>();
            this.CadastroDivida = new HashSet<CadastroDivida>();
            this.CadastroImplemento = new HashSet<CadastroImplemento>();
            this.CadastroMaquina = new HashSet<CadastroMaquina>();
            this.CadastroRelacao = new HashSet<CadastroRelacao>();
            this.CadastroSemovente = new HashSet<CadastroSemovente>();
            this.CadastroTerraSolo = new HashSet<CadastroTerraSolo>();
            this.CadastroVeiculo = new HashSet<CadastroVeiculo>();
            this.SafraNormalPrevista = new HashSet<SafraNormalPrevista>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public string DataExpedicao { get; set; }
        public string CPF { get; set; }
        public string DataNascimento { get; set; }
        public string Naturalidade { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public string Endereco { get; set; }
        public string CEP { get; set; }
        public string RendaMensal { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Ocupacao { get; set; }
        public string Grau { get; set; }
        public string Formacao { get; set; }
    
        public virtual ICollection<CadastroBenfeitoria> CadastroBenfeitoria { get; set; }
        public virtual ICollection<CadastroBensDireitos> CadastroBensDireitos { get; set; }
        public virtual ICollection<CadastroClientes> CadastroClientes { get; set; }
        public virtual ICollection<CadastroDivida> CadastroDivida { get; set; }
        public virtual ICollection<CadastroImplemento> CadastroImplemento { get; set; }
        public virtual ICollection<CadastroMaquina> CadastroMaquina { get; set; }
        public virtual ICollection<CadastroRelacao> CadastroRelacao { get; set; }
        public virtual ICollection<CadastroSemovente> CadastroSemovente { get; set; }
        public virtual ICollection<CadastroTerraSolo> CadastroTerraSolo { get; set; }
        public virtual ICollection<CadastroVeiculo> CadastroVeiculo { get; set; }
        public virtual ICollection<SafraNormalPrevista> SafraNormalPrevista { get; set; }
    }
}
