//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroSafra
    {
        public CadastroSafra()
        {
            this.SafraNormalPrevista = new HashSet<SafraNormalPrevista>();
            this.SafraDistribuicao = new HashSet<SafraDistribuicao>();
        }
    
        public int ID { get; set; }
        public string SafraData { get; set; }
        public string NomeSafra { get; set; }
        public Nullable<bool> SafraPrevista { get; set; }
    
        public virtual ICollection<SafraNormalPrevista> SafraNormalPrevista { get; set; }
        public virtual ICollection<SafraDistribuicao> SafraDistribuicao { get; set; }
    }
}
