//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroBensDireitos
    {
        public int ID { get; set; }
        public string BensDireitosCategoria { get; set; }
        public string BensDireitosCaracteristicas { get; set; }
        public double BensDireitosValor { get; set; }
        public int BensDireitosUsuarioID { get; set; }
    
        public virtual CadastroUsuarios CadastroUsuarios { get; set; }
    }
}
