//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroSemovente
    {
        public int ID { get; set; }
        public string SemoventeEspecificacao { get; set; }
        public short SemoventeUA { get; set; }
        public short SemoventeNumeroUA { get; set; }
        public short SemoventeNumeroCabecas { get; set; }
        public string SemoventeCaracteristicas { get; set; }
        public double SemoventeValorUnitario { get; set; }
        public string SemoventeCredor { get; set; }
        public int SemoventeUsuarioID { get; set; }
        public int SemoventeFazendaID { get; set; }
        public Nullable<bool> SemoventeP { get; set; }
    
        public virtual CadastroFazenda CadastroFazenda { get; set; }
        public virtual CadastroUsuarios CadastroUsuarios { get; set; }
    }
}
