//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroFazenda
    {
        public CadastroFazenda()
        {
            this.CadastroBenfeitoria = new HashSet<CadastroBenfeitoria>();
            this.CadastroRelacao = new HashSet<CadastroRelacao>();
            this.CadastroSemovente = new HashSet<CadastroSemovente>();
            this.CadastroTerraSolo = new HashSet<CadastroTerraSolo>();
            this.SafraDistribuicao = new HashSet<SafraDistribuicao>();
        }
    
        public int ID { get; set; }
        public string FazendaNome { get; set; }
        public string FazendaMatriculaCRI { get; set; }
        public string FazendaCodigoINCRA { get; set; }
        public string FazendaMunicipio { get; set; }
        public string FazendaRoteiroAcesso { get; set; }
        public string FazendaConfrontacoesNorte { get; set; }
        public string FazendaConfrontacoesSul { get; set; }
        public string FazendaConfrontacoesLeste { get; set; }
        public string FazendaConfrontacoesOeste { get; set; }
        public string FazendaTitulosDominio { get; set; }
        public string FazendaTipoPropriedade { get; set; }
        public string FazendaOnusGravames { get; set; }
        public string FazendaMatricula { get; set; }
        public string FazendaCodReceitaFederal { get; set; }
        public double FazendaBeneficioSoloSaca { get; set; }
        public double FazendaBeneficioSoloValorUnitario { get; set; }
        public int FazendaMicrorregiao { get; set; }
        public int FazendaCultura { get; set; }
        public Nullable<bool> FazendaArrendada { get; set; }
        public Nullable<double> FazendaArrendadaAreaArrendada { get; set; }
        public Nullable<double> FazendaArrendadaValorArrendado { get; set; }
        public Nullable<System.DateTime> FazendaArrendadaDataInicio { get; set; }
        public Nullable<System.DateTime> FazendaArrendadaDataFim { get; set; }
    
        public virtual ICollection<CadastroBenfeitoria> CadastroBenfeitoria { get; set; }
        public virtual CadastroMicrorregiao CadastroMicrorregiao { get; set; }
        public virtual Cultura Cultura { get; set; }
        public virtual ICollection<CadastroRelacao> CadastroRelacao { get; set; }
        public virtual ICollection<CadastroSemovente> CadastroSemovente { get; set; }
        public virtual ICollection<CadastroTerraSolo> CadastroTerraSolo { get; set; }
        public virtual ICollection<SafraDistribuicao> SafraDistribuicao { get; set; }
    }
}
