//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroRelacao
    {
        public int ID { get; set; }
        public int RelacaoUsuarioID { get; set; }
        public Nullable<int> RelacaoFazendaID { get; set; }
        public int RelacaoTitulo { get; set; }
    
        public virtual CadastroFazenda CadastroFazenda { get; set; }
        public virtual CadastroUsuarios CadastroUsuarios { get; set; }
    }
}
