//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroBenfeitoria
    {
        public int ID { get; set; }
        public int BenfeitoriaFazenda { get; set; }
        public string BenfeitoriaEspecificacao { get; set; }
        public int BenfeitoriaQuantidade { get; set; }
        public string BenfeitoriaCaracteristicas { get; set; }
        public string BenfeitoriaAno { get; set; }
        public string BenfeitoriaEstadoConservacao { get; set; }
        public Nullable<bool> BenfeitoriaArrendado { get; set; }
        public Nullable<System.DateTime> BenfeitoriaData { get; set; }
        public Nullable<bool> BenfeitoriaAtiva { get; set; }
        public double BenfeitoriaValor { get; set; }
        public Nullable<int> BenfeitoriaUsuario { get; set; }
        public Nullable<double> BenfeitoriaParticipacao { get; set; }
    
        public virtual CadastroFazenda CadastroFazenda { get; set; }
        public virtual CadastroUsuarios CadastroUsuarios { get; set; }
    }
}
