//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroClientes
    {
        public int ID { get; set; }
        public string ClienteExperiencia { get; set; }
        public string ClienteClassificacaoPorte { get; set; }
        public string ClienteAtividadeDesenvolvida { get; set; }
        public string ClienteTempoAtividade { get; set; }
        public string ClienteEstruturaArmazenamento { get; set; }
        public string ClienteEstruturaTransporte { get; set; }
        public string ClienteResidenciaProdutor { get; set; }
        public string ClienteEstadoCivil { get; set; }
        public Nullable<int> ClienteAuthority { get; set; }
        public int ClienteDadosUsuario { get; set; }
        public Nullable<int> ClienteRelacaoFazenda { get; set; }
        public Nullable<int> ClienteFazenda { get; set; }
        public Nullable<int> ClienteConjujeUsuario { get; set; }
        public Nullable<double> ClienteParticipacaoGeral { get; set; }
        public string ClienteListaSociosID { get; set; }
        public string ClienteListaSociosNome { get; set; }
        public string ClienteGrau { get; set; }
        public string ClienteFormacao { get; set; }
    
        public virtual CadastroUsuarios CadastroUsuarios { get; set; }
    }
}
