//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroMicrorregiao
    {
        public CadastroMicrorregiao()
        {
            this.CadastroFazenda = new HashSet<CadastroFazenda>();
        }
    
        public int ID { get; set; }
        public string MicrorregiaoNome { get; set; }
        public int MicrorregiaoBrutaNuaInferiorSaca { get; set; }
        public int MicrorregiaoBrutaNuaSuperiorSaca { get; set; }
        public int MicrorregiaoCurrigidaCultivadaInferiorSaca { get; set; }
        public int MicrorregiaoCurrigidaCultivadaSuperiorSaca { get; set; }
        public Nullable<bool> Ativa { get; set; }
    
        public virtual ICollection<CadastroFazenda> CadastroFazenda { get; set; }
    }
}
