//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroDivida
    {
        public int ID { get; set; }
        public string DividaCredor { get; set; }
        public string DividaFinalidade { get; set; }
        public string DividaDataContratada { get; set; }
        public string DividaDataVencimento { get; set; }
        public string DividaCarencia { get; set; }
        public string DividaEncargos { get; set; }
        public string DividaPeriodicidade { get; set; }
        public double DividaSaldo { get; set; }
        public int DividaUsuario { get; set; }
        public Nullable<System.DateTime> DividaData { get; set; }
        public Nullable<int> DividaSafra { get; set; }
        public Nullable<bool> DividaAtiva { get; set; }
    
        public virtual CadastroUsuarios CadastroUsuarios { get; set; }
    }
}
