//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteFazenda
    {
        public string ClienteTempoAtividade { get; set; }
        public string ClienteEstadoCivil { get; set; }
        public Nullable<int> ClienteAuthority { get; set; }
        public string UsuarioNome { get; set; }
        public string ConjugeUsuarioNome { get; set; }
        public Nullable<int> ClienteConjujeUsuario { get; set; }
        public int IDUsuario { get; set; }
        public Nullable<int> ConjugeID { get; set; }
        public int IDCliente { get; set; }
        public string ClienteListaSociosID { get; set; }
        public string ClienteListaSociosNome { get; set; }
        public Nullable<double> ClienteParticipacaoGeral { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
