//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cultura
    {
        public Cultura()
        {
            this.CadastroFazenda = new HashSet<CadastroFazenda>();
            this.SafraNormalPrevista = new HashSet<SafraNormalPrevista>();
            this.SafraDistribuicao = new HashSet<SafraDistribuicao>();
        }
    
        public int ID { get; set; }
        public string NomeCultura { get; set; }
        public double ValorSaca { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<bool> UsarCultura { get; set; }
        public Nullable<bool> CulturaCalculo { get; set; }
    
        public virtual ICollection<CadastroFazenda> CadastroFazenda { get; set; }
        public virtual ICollection<SafraNormalPrevista> SafraNormalPrevista { get; set; }
        public virtual ICollection<SafraDistribuicao> SafraDistribuicao { get; set; }
    }
}
