//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SCPEntities : DbContext
    {
        public SCPEntities()
            : base("name=SCPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHORITY> AUTHORITY { get; set; }
        public virtual DbSet<CadastroBenfeitoria> CadastroBenfeitoria { get; set; }
        public virtual DbSet<CadastroBensDireitos> CadastroBensDireitos { get; set; }
        public virtual DbSet<CadastroClientes> CadastroClientes { get; set; }
        public virtual DbSet<CadastroDivida> CadastroDivida { get; set; }
        public virtual DbSet<CadastroFazenda> CadastroFazenda { get; set; }
        public virtual DbSet<CadastroImplemento> CadastroImplemento { get; set; }
        public virtual DbSet<CadastroMaquina> CadastroMaquina { get; set; }
        public virtual DbSet<CadastroMicrorregiao> CadastroMicrorregiao { get; set; }
        public virtual DbSet<CadastroQuestionario> CadastroQuestionario { get; set; }
        public virtual DbSet<CadastroRelacao> CadastroRelacao { get; set; }
        public virtual DbSet<CadastroRespostaQuestionario> CadastroRespostaQuestionario { get; set; }
        public virtual DbSet<CadastroSafra> CadastroSafra { get; set; }
        public virtual DbSet<CadastroSemovente> CadastroSemovente { get; set; }
        public virtual DbSet<CadastroTerraSolo> CadastroTerraSolo { get; set; }
        public virtual DbSet<CadastroUsuarios> CadastroUsuarios { get; set; }
        public virtual DbSet<CadastroVeiculo> CadastroVeiculo { get; set; }
        public virtual DbSet<Cultura> Cultura { get; set; }
        public virtual DbSet<LimiteCreditos> LimiteCreditos { get; set; }
        public virtual DbSet<TerraSolo> TerraSolo { get; set; }
        public virtual DbSet<SafraNormalPrevista> SafraNormalPrevista { get; set; }
        public virtual DbSet<BenfeitoriaFazenda> BenfeitoriaFazenda { get; set; }
        public virtual DbSet<ClienteConjuge> ClienteConjuge { get; set; }
        public virtual DbSet<ClienteFazenda> ClienteFazenda { get; set; }
        public virtual DbSet<DividaUsuario> DividaUsuario { get; set; }
        public virtual DbSet<FazendaRelacao> FazendaRelacao { get; set; }
        public virtual DbSet<FazendaTotals> FazendaTotals { get; set; }
        public virtual DbSet<funcaodistribuicaoAreaSafra> funcaodistribuicaoAreaSafra { get; set; }
        public virtual DbSet<ImplementoFazendaUsuario> ImplementoFazendaUsuario { get; set; }
        public virtual DbSet<LimiteCredito> LimiteCredito { get; set; }
        public virtual DbSet<MaquinaFazendaUsuario> MaquinaFazendaUsuario { get; set; }
        public virtual DbSet<Proprietarios> Proprietarios { get; set; }
        public virtual DbSet<QuestionarioResposta> QuestionarioResposta { get; set; }
        public virtual DbSet<ResumoFazendas> ResumoFazendas { get; set; }
        public virtual DbSet<TerraSoloFazenda> TerraSoloFazenda { get; set; }
        public virtual DbSet<UsuarioSafrasNormalPrevista> UsuarioSafrasNormalPrevista { get; set; }
        public virtual DbSet<UsuariosFazenda> UsuariosFazenda { get; set; }
        public virtual DbSet<VeiculoFazendaUsuario> VeiculoFazendaUsuario { get; set; }
        public virtual DbSet<VerificacaoDadosGerais> VerificacaoDadosGerais { get; set; }
        public virtual DbSet<SafraDistribuicao> SafraDistribuicao { get; set; }
        public virtual DbSet<DistribuicaoSafraFazenda> DistribuicaoSafraFazenda { get; set; }
    
        public virtual int CloneCadastroPatrimonio(Nullable<int> userClone, Nullable<int> cloneUser)
        {
            var userCloneParameter = userClone.HasValue ?
                new ObjectParameter("UserClone", userClone) :
                new ObjectParameter("UserClone", typeof(int));
    
            var cloneUserParameter = cloneUser.HasValue ?
                new ObjectParameter("CloneUser", cloneUser) :
                new ObjectParameter("CloneUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CloneCadastroPatrimonio", userCloneParameter, cloneUserParameter);
        }
    
        public virtual int DestroiCadastro(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DestroiCadastro", userIDParameter);
        }
    
        public virtual int InsertLimiteCredito(Nullable<int> safra, Nullable<int> cliente)
        {
            var safraParameter = safra.HasValue ?
                new ObjectParameter("Safra", safra) :
                new ObjectParameter("Safra", typeof(int));
    
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLimiteCredito", safraParameter, clienteParameter);
        }
    
        public virtual int Proc_LimiteCredito(string campoIdentityID)
        {
            var campoIdentityIDParameter = campoIdentityID != null ?
                new ObjectParameter("CampoIdentityID", campoIdentityID) :
                new ObjectParameter("CampoIdentityID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_LimiteCredito", campoIdentityIDParameter);
        }
    
        public virtual ObjectResult<Proc_Questoes_Result> Proc_Questoes(Nullable<int> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("IdUser", idUser) :
                new ObjectParameter("IdUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Questoes_Result>("Proc_Questoes", idUserParameter);
        }
    
        public virtual ObjectResult<RF_Result> RF(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RF_Result>("RF", userIDParameter);
        }
    }
}
