//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SCPEntities : DbContext
    {
        public SCPEntities()
            : base("name=SCPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AUTHORITY> AUTHORITY { get; set; }
        public DbSet<CadastroBenfeitoria> CadastroBenfeitoria { get; set; }
        public DbSet<CadastroClientes> CadastroClientes { get; set; }
        public DbSet<CadastroDivida> CadastroDivida { get; set; }
        public DbSet<CadastroFazenda> CadastroFazenda { get; set; }
        public DbSet<CadastroImplemento> CadastroImplemento { get; set; }
        public DbSet<CadastroMaquina> CadastroMaquina { get; set; }
        public DbSet<CadastroMicrorregiao> CadastroMicrorregiao { get; set; }
        public DbSet<CadastroQuestionario> CadastroQuestionario { get; set; }
        public DbSet<CadastroRelacao> CadastroRelacao { get; set; }
        public DbSet<CadastroRespostaQuestionario> CadastroRespostaQuestionario { get; set; }
        public DbSet<CadastroSafra> CadastroSafra { get; set; }
        public DbSet<CadastroTerraSolo> CadastroTerraSolo { get; set; }
        public DbSet<CadastroUsuarios> CadastroUsuarios { get; set; }
        public DbSet<CadastroVeiculo> CadastroVeiculo { get; set; }
        public DbSet<CadastroVeiculoChecked> CadastroVeiculoChecked { get; set; }
        public DbSet<Cultura> Cultura { get; set; }
        public DbSet<MasterFazenda> MasterFazenda { get; set; }
        public DbSet<MasterUsuario> MasterUsuario { get; set; }
        public DbSet<BenfeitoriaFazenda> BenfeitoriaFazenda { get; set; }
        public DbSet<ClienteConjuge> ClienteConjuge { get; set; }
        public DbSet<ClienteFazenda> ClienteFazenda { get; set; }
        public DbSet<DividaUsuario> DividaUsuario { get; set; }
        public DbSet<ImplementoFazendaUsuario> ImplementoFazendaUsuario { get; set; }
        public DbSet<LimiteCredito> LimiteCredito { get; set; }
        public DbSet<MaquinaFazendaUsuario> MaquinaFazendaUsuario { get; set; }
        public DbSet<QuestionarioResposta> QuestionarioResposta { get; set; }
        public DbSet<TerraSoloFazenda> TerraSoloFazenda { get; set; }
        public DbSet<VeiculoFazendaUsuario> VeiculoFazendaUsuario { get; set; }
        public DbSet<VerificacaoDadosGerais> VerificacaoDadosGerais { get; set; }
    
        public virtual ObjectResult<Cliente_UsuarioFazenda_Result> Cliente_UsuarioFazenda(Nullable<int> campoID)
        {
            var campoIDParameter = campoID.HasValue ?
                new ObjectParameter("CampoID", campoID) :
                new ObjectParameter("CampoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cliente_UsuarioFazenda_Result>("Cliente_UsuarioFazenda", campoIDParameter);
        }
    
        public virtual ObjectResult<Proc_LimiteCredito_Result> Proc_LimiteCredito(string campoIdentityID)
        {
            var campoIdentityIDParameter = campoIdentityID != null ?
                new ObjectParameter("CampoIdentityID", campoIdentityID) :
                new ObjectParameter("CampoIdentityID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LimiteCredito_Result>("Proc_LimiteCredito", campoIdentityIDParameter);
        }
    }
}
