//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistribuicaoSafraFazenda
    {
        public int ID { get; set; }
        public string DistribuicaoSafraTipo { get; set; }
        public int DistribuicaoSafraFazenda1 { get; set; }
        public Nullable<int> DistribuicaoSafraSistemaPlantio { get; set; }
        public Nullable<double> DistribuicaoSafraArea { get; set; }
        public int DistribuicaoSafraUsuarioID { get; set; }
        public string FazendaNome { get; set; }
        public Nullable<int> RelacaoTitulo { get; set; }
        public string Nome { get; set; }
        public Nullable<int> IDProprietário { get; set; }
        public int IDFazenda { get; set; }
        public string FazendaMunicipio { get; set; }
        public Nullable<bool> FazendaArrendada { get; set; }
        public string FazendaOnusGravames { get; set; }
        public int DistribuicaoSafraSafra { get; set; }
        public string NomeSafra { get; set; }
        public string NomeCultura { get; set; }
        public Nullable<bool> SafraPrevista { get; set; }
    }
}
