//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FazendaTotals
    {
        public int ID { get; set; }
        public string FazendaNome { get; set; }
        public double FazendaBeneficioSoloSaca { get; set; }
        public double FazendaBeneficioSoloValorUnitario { get; set; }
        public Nullable<double> ValorTotal { get; set; }
        public Nullable<double> AreaTotal { get; set; }
        public Nullable<double> ValorParticipacao { get; set; }
        public Nullable<double> BeneficioSolo { get; set; }
        public Nullable<int> RelacaoUsuarioID { get; set; }
        public Nullable<double> AreaCultivada { get; set; }
        public Nullable<double> ValorTerraNua { get; set; }
        public Nullable<int> IDMicrorregiao { get; set; }
        public string MicrorregiaoNome { get; set; }
        public Nullable<int> IDCultura { get; set; }
        public string NomeCultura { get; set; }
        public string FazendaMunicipio { get; set; }
        public Nullable<int> MicrorregiaoBrutaNuaInferiorSaca { get; set; }
        public Nullable<int> MicrorregiaoBrutaNuaSuperiorSaca { get; set; }
        public Nullable<int> MicrorregiaoCurrigidaCultivadaInferiorSaca { get; set; }
        public Nullable<int> MicrorregiaoCurrigidaCultivadaSuperiorSaca { get; set; }
        public Nullable<double> FazendaParticipacao { get; set; }
        public Nullable<int> TotalBenfeitoriaChecked { get; set; }
        public Nullable<double> TotalValorBenfeitoriaChecked { get; set; }
        public Nullable<double> ValorParticipacaoBenfeitoria { get; set; }
        public Nullable<int> RelacaoTitulo { get; set; }
        public string NomeProprietario { get; set; }
        public Nullable<bool> FazendaArrendada { get; set; }
        public Nullable<double> TotaisSemovente { get; set; }
        public Nullable<double> TotalArrendado { get; set; }
        public double ValorSaca { get; set; }
    }
}
