//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImplementoFazendaUsuario
    {
        public string FazendaNome { get; set; }
        public string Nome { get; set; }
        public int ID { get; set; }
        public string ImplementoEspecificacao { get; set; }
        public string ImplementoMarca { get; set; }
        public Nullable<int> ImplementoFazendaOrigem { get; set; }
        public string ImplementoP { get; set; }
        public double ImplementoValor { get; set; }
        public string ImplementoChassiSerie { get; set; }
        public string ImplementoEstado { get; set; }
        public string ImplementoAno { get; set; }
        public string ImplementoModelo { get; set; }
        public string ImplementoCidadeLocal { get; set; }
        public Nullable<System.DateTime> ImplementoData { get; set; }
        public Nullable<bool> ImplementoAtiva { get; set; }
        public int ImplementoUsuario { get; set; }
        public Nullable<int> IDFazenda { get; set; }
        public Nullable<double> RelacaoParticipacao { get; set; }
    }
}
