//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimiteCreditos
    {
        public int ID { get; set; }
        public string EntidadeTipo { get; set; }
        public int EntidadeID { get; set; }
        public string EntidadeSafra { get; set; }
        public string EntidadeHash { get; set; }
        public string EntidadeReferencia { get; set; }
        public Nullable<int> EntidadeReferenciaValor { get; set; }
        public string Campo1 { get; set; }
        public string Campo2 { get; set; }
        public string Campo3 { get; set; }
        public string Campo4 { get; set; }
        public string Campo5 { get; set; }
        public string Campo6 { get; set; }
        public string Campo7 { get; set; }
        public string Campo8 { get; set; }
        public string Campo9 { get; set; }
        public string Campo10 { get; set; }
        public string Campo11 { get; set; }
        public string Campo12 { get; set; }
        public string Campo13 { get; set; }
        public string Campo14 { get; set; }
        public string Campo15 { get; set; }
        public string Campo16 { get; set; }
        public string Campo17 { get; set; }
        public string Campo18 { get; set; }
        public string Campo19 { get; set; }
        public string Campo20 { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public Nullable<System.DateTime> EntidadeDataCadastro { get; set; }
        public string Campo21 { get; set; }
        public string Campo22 { get; set; }
        public string Campo23 { get; set; }
        public string Campo24 { get; set; }
        public string Campo25 { get; set; }
    }
}
