//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimiteCredito
    {
        public string EntidadeTipo { get; set; }
        public int EntidadeID { get; set; }
        public string EntidadeSafra { get; set; }
        public string EntidadeHash { get; set; }
        public string EntidadeReferencia { get; set; }
        public Nullable<int> EntidadeReferenciaValor { get; set; }
        public Nullable<System.DateTime> EntidadeDataCadastro { get; set; }
        public string Campo1 { get; set; }
        public string NomeSafra { get; set; }
    }
}
