//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaquinaFazendaUsuario
    {
        public string FazendaNome { get; set; }
        public string Nome { get; set; }
        public int ID { get; set; }
        public string MaquinaEspecificacao { get; set; }
        public string MaquinaMarca { get; set; }
        public string MaquinaModelo { get; set; }
        public string MaquinaPotencia { get; set; }
        public string MaquinaAno { get; set; }
        public string MaquinaEstado { get; set; }
        public string MaquinaChassiSerie { get; set; }
        public double MaquinaValor { get; set; }
        public string MaquinaP { get; set; }
        public Nullable<int> MaquinaFazendaOrigem { get; set; }
        public string MaquinaCidadeLocal { get; set; }
        public Nullable<bool> MaquinaAtiva { get; set; }
        public Nullable<System.DateTime> MaquinaData { get; set; }
        public int IDUsuario { get; set; }
        public int MaquinaUsuario { get; set; }
        public Nullable<double> RelacaoParticipacao { get; set; }
    }
}
