//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proprietarios
    {
        public Nullable<int> ID { get; set; }
        public string Nome { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public int IDCliente { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public Nullable<int> RelacaoTitulo { get; set; }
    }
}
