//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionarioResposta
    {
        public int ID { get; set; }
        public string QuestionarioQuestao { get; set; }
        public Nullable<int> QuestionarioRespostaQuestao { get; set; }
        public Nullable<int> QuestionarioRespostaUsuario { get; set; }
        public string QuestionarioRespostaResposta1 { get; set; }
    }
}
