//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumoFazendas
    {
        public int ID { get; set; }
        public Nullable<int> QTDMaquinas { get; set; }
        public Nullable<int> QTDImplementos { get; set; }
        public Nullable<int> QTDVeiculos { get; set; }
        public Nullable<int> QTDTerrasSolos { get; set; }
        public Nullable<int> QTDBenfeitorias { get; set; }
        public Nullable<int> QTDSemoventes { get; set; }
        public Nullable<double> ClienteParticipacaoGeral { get; set; }
        public Nullable<double> TotalTerraSolo { get; set; }
        public Nullable<double> TotalBenfeitorias { get; set; }
        public Nullable<double> TotalSemoventes { get; set; }
        public Nullable<double> ResumoMaquina { get; set; }
        public Nullable<double> ResumoVeiculo { get; set; }
        public Nullable<double> ResumoImplemento { get; set; }
        public Nullable<double> ResumoBensDireitos { get; set; }
    }
}
