//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafraNormalPrevista
    {
        public int ID { get; set; }
        public int SafrasSafra { get; set; }
        public int SafrasSistemaPlantio { get; set; }
        public double SafrasArea { get; set; }
        public double SafrasProdutividade { get; set; }
        public double SafrasValorUnitario { get; set; }
        public double SafrasCustoUnitario { get; set; }
        public int SafrasUsuarioID { get; set; }
        public string SafrasObservacao { get; set; }
        public int SafrasCultura { get; set; }
    
        public virtual CadastroSafra CadastroSafra { get; set; }
        public virtual CadastroUsuarios CadastroUsuarios { get; set; }
        public virtual Cultura Cultura { get; set; }
    }
}
