//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafraDistribuicao
    {
        public int ID { get; set; }
        public string DistribuicaoSafraTipo { get; set; }
        public int DistribuicaoSafraFazenda { get; set; }
        public Nullable<int> DistribuicaoSafraSistemaPlantio { get; set; }
        public Nullable<double> DistribuicaoSafraArea { get; set; }
        public int DistribuicaoSafraUsuarioID { get; set; }
        public int DistribuicaoSafraSafra { get; set; }
        public Nullable<int> DistribuicaoSafraCultura { get; set; }
        public string DistribuicaoSafraObservacaoGravame { get; set; }
    
        public virtual CadastroFazenda CadastroFazenda { get; set; }
        public virtual CadastroSafra CadastroSafra { get; set; }
        public virtual Cultura Cultura { get; set; }
    }
}
