//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerraSoloFazenda
    {
        public int IDSOLO { get; set; }
        public string FazendaNome { get; set; }
        public Nullable<int> FazendaID { get; set; }
        public string FazendaMatriculaCRI { get; set; }
        public string FazendaCodigoINCRA { get; set; }
        public string TerraSoloClasse { get; set; }
        public string TerraSoloCaracteristicas { get; set; }
        public int TerraSoloEspecificacao { get; set; }
        public string FazendaMunicipio { get; set; }
        public string FazendaRoteiroAcesso { get; set; }
        public string FazendaConfrontacoesNorte { get; set; }
        public string FazendaOnusGravames { get; set; }
        public string FazendaTipoPropriedade { get; set; }
        public string FazendaConfrontacoesLeste { get; set; }
        public string FazendaConfrontacoesOeste { get; set; }
        public string FazendaTitulosDominio { get; set; }
        public string FazendaConfrontacoesSul { get; set; }
        public Nullable<bool> TerraSoloAtiva { get; set; }
        public int TerraSoloFazenda1 { get; set; }
        public string MicrorregiaoNome { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public string NomeCultura { get; set; }
        public Nullable<int> TerraSoloSacas { get; set; }
        public string tipo { get; set; }
        public Nullable<double> ValorTotal { get; set; }
        public double TerraSoloArea { get; set; }
        public Nullable<int> ID { get; set; }
        public int TerraSoloMicrorregiaoTerra { get; set; }
        public int TerraSoloTipoCultura { get; set; }
        public int TerraSoloMicrorregiao { get; set; }
        public Nullable<double> ValorUnitario { get; set; }
        public Nullable<int> TerraSoloUsuario { get; set; }
        public Nullable<int> RelacaoTitulo { get; set; }
    }
}
