//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerraSolo
    {
        public TerraSolo()
        {
            this.CadastroTerraSolo = new HashSet<CadastroTerraSolo>();
        }
    
        public int ID { get; set; }
        public string tipo { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual ICollection<CadastroTerraSolo> CadastroTerraSolo { get; set; }
    }
}
