//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSafrasNormalPrevista
    {
        public int ID { get; set; }
        public int SafrasSafra { get; set; }
        public int SafrasSistemaPlantio { get; set; }
        public double SafrasArea { get; set; }
        public double SafrasProdutividade { get; set; }
        public double SafrasValorUnitario { get; set; }
        public int SafrasUsuarioID { get; set; }
        public string SafrasObservacao { get; set; }
        public double SafrasCustoUnitario { get; set; }
        public double CustoTotal { get; set; }
        public double ValorReceita { get; set; }
        public string Nome { get; set; }
        public string NomeSafra { get; set; }
        public int SafrasCultura { get; set; }
        public string NomeCultura { get; set; }
        public Nullable<bool> SafraPrevista { get; set; }
    }
}
