//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosFazenda
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public int RelacaoTitulo { get; set; }
        public string RG { get; set; }
        public string DataExpedicao { get; set; }
        public string CPF { get; set; }
        public string DataNascimento { get; set; }
        public string Naturalidade { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public string Endereco { get; set; }
        public string CEP { get; set; }
        public string RendaMensal { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public Nullable<int> RelacaoFazendaID { get; set; }
        public string Ocupacao { get; set; }
    }
}
