//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeiculoFazendaUsuario
    {
        public int ID { get; set; }
        public string VeiculoEspecificacao { get; set; }
        public string VeiculoMarca { get; set; }
        public string VeiculoModelo { get; set; }
        public string VeiculoPotencia { get; set; }
        public string VeiculoAno { get; set; }
        public string VeiculoEstado { get; set; }
        public string VeiculoChassiSerie { get; set; }
        public double VeiculoValor { get; set; }
        public string VeiculoP { get; set; }
        public Nullable<int> VeiculoFazendaOrigem { get; set; }
        public string VeiculoCidadeLocal { get; set; }
        public string Nome { get; set; }
        public string FazendaNome { get; set; }
        public Nullable<bool> VeiculoAtiva { get; set; }
        public Nullable<System.DateTime> VeiculoData { get; set; }
        public int IDUsuario { get; set; }
        public Nullable<int> IDFazenda { get; set; }
        public Nullable<double> RelacaoParticipacao { get; set; }
    }
}
