//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCP___AgroGerente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificacaoDadosGerais
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string ClienteGrau { get; set; }
        public string ClienteFormacao { get; set; }
        public string ClienteExperiencia { get; set; }
        public string ClienteClassificacaoPorte { get; set; }
        public string ClienteAtividadeDesenvolvida { get; set; }
        public string ClienteTempoAtividade { get; set; }
        public string ClienteEstruturaArmazenamento { get; set; }
        public string ClienteEstruturaTransporte { get; set; }
        public string ClienteResidenciaProdutor { get; set; }
        public string ClienteEstadoCivil { get; set; }
        public string ClienteDadosUsuario { get; set; }
        public string ClienteFazenda { get; set; }
        public string ClienteRelacaoFazenda { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public string UsuarioRG { get; set; }
        public string UsuarioDataExpedicao { get; set; }
        public string UsuarioCPF { get; set; }
        public string UsuarioDataNascimento { get; set; }
        public string UsuarioNaturalidade { get; set; }
        public string UsuarioTelefone1 { get; set; }
        public string UsuarioCelular1 { get; set; }
        public string UsuarioEndereco { get; set; }
        public string UsuarioCEP { get; set; }
        public string UsuarioRendaMensal { get; set; }
        public string UsuarioCidade { get; set; }
        public string UsuarioEstado { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public Nullable<int> RelacaoTitulo { get; set; }
        public Nullable<int> QuantidadeFazendas { get; set; }
    }
}
